In [1]:
import numpy as nm

In [2]:
import matplotlib.pyplot as mtp

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('C:/Users/Ajay/Desktop/ML/Logistic Regression/Breast_Cancer_Data.csv')

In [5]:
print(data)

           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [6]:
print(data.iloc[:,[2,3]])

     radius_mean  texture_mean
0          17.99         10.38
1          20.57         17.77
2          19.69         21.25
3          11.42         20.38
4          20.29         14.34
..           ...           ...
564        21.56         22.39
565        20.13         28.25
566        16.60         28.08
567        20.60         29.33
568         7.76         24.54

[569 rows x 2 columns]


In [7]:
#Independent variable continuous: radius, texture
x= data.iloc[:,[2,3]].values
print(x)

[[17.99 10.38]
 [20.57 17.77]
 [19.69 21.25]
 ...
 [16.6  28.08]
 [20.6  29.33]
 [ 7.76 24.54]]


In [8]:
#Dependent variable categorical: diagnosis
y= data.iloc[:,1].values
print(y)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B

In [9]:
#Splitting into training and test set
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 1/3, random_state=0)

In [11]:
print(x_test)

[[13.4   20.52 ]
 [13.21  25.25 ]
 [14.02  15.66 ]
 [14.26  18.17 ]
 [13.03  18.42 ]
 [11.34  18.61 ]
 [12.05  22.72 ]
 [11.7   19.11 ]
 [ 7.729 25.49 ]
 [10.26  14.71 ]
 [14.69  13.98 ]
 [14.62  24.02 ]
 [ 9.397 21.68 ]
 [16.84  19.46 ]
 [14.64  15.24 ]
 [15.46  11.89 ]
 [ 9.042 18.9  ]
 [20.51  27.81 ]
 [19.55  23.21 ]
 [20.94  23.56 ]
 [11.84  18.7  ]
 [16.24  18.77 ]
 [13.47  14.06 ]
 [11.84  18.94 ]
 [21.37  15.1  ]
 [11.93  10.91 ]
 [10.9   12.96 ]
 [13.73  22.61 ]
 [13.4   16.95 ]
 [18.77  21.43 ]
 [12.81  13.06 ]
 [20.57  17.77 ]
 [13.14  20.74 ]
 [16.16  21.54 ]
 [ 9.738 11.97 ]
 [12.68  23.84 ]
 [13.27  17.02 ]
 [19.    18.91 ]
 [14.86  16.94 ]
 [15.08  25.74 ]
 [15.13  29.81 ]
 [ 8.878 15.49 ]
 [16.02  23.24 ]
 [10.32  16.35 ]
 [13.24  20.13 ]
 [21.56  22.39 ]
 [ 8.671 14.45 ]
 [14.03  21.25 ]
 [11.81  17.39 ]
 [14.54  27.54 ]
 [19.17  24.8  ]
 [14.86  23.21 ]
 [18.45  21.91 ]
 [11.6   18.36 ]
 [12.46  19.89 ]
 [11.47  16.03 ]
 [11.32  27.08 ]
 [12.27  29.97 ]
 [12.18  20.52

In [12]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [13]:
print(x_test)

[[-2.34330752e-01  3.05543378e-01]
 [-2.86991566e-01  1.43128007e+00]
 [-6.24901993e-02 -8.51133228e-01]
 [ 4.02872416e-03 -2.53754981e-01]
 [-3.36880759e-01 -1.94255156e-01]
 [-8.05284845e-01 -1.49035288e-01]
 [-6.08499696e-01  8.29141841e-01]
 [-7.05506460e-01 -3.00356375e-02]
 [-1.80611748e+00  1.48839991e+00]
 [-1.10462000e+00 -1.07723256e+00]
 [ 1.23208462e-01 -1.25097205e+00]
 [ 1.03807109e-01  1.13854093e+00]
 [-1.34381096e+00  5.81622568e-01]
 [ 7.19107152e-01  5.32641181e-02]
 [ 1.09350353e-01 -9.51092935e-01]
 [ 3.36623342e-01 -1.74839059e+00]
 [-1.44220354e+00 -8.00154908e-02]
 [ 1.73629236e+00  2.04055829e+00]
 [ 1.47021666e+00  9.45761499e-01]
 [ 1.85547210e+00  1.02906125e+00]
 [-6.66703755e-01 -1.27615351e-01]
 [ 5.52809843e-01 -1.10955400e-01]
 [-2.14929399e-01 -1.23193211e+00]
 [-6.66703755e-01 -7.04955187e-02]
 [ 1.97465183e+00 -9.84412837e-01]
 [-6.41759158e-01 -1.98162991e+00]
 [-9.27236205e-01 -1.49373134e+00]
 [-1.42867232e-01  8.02961918e-01]
 [-2.34330752e-01 -5

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
classifier= LogisticRegression(random_state=0)

In [16]:
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [17]:
y_pred = classifier.predict(x_test)

In [18]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test,y_pred) 
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[115   7]
 [ 10  58]]


In [19]:
#Accuracy score
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9105263157894737
